In [1]:
import nglview as nv
import calc
import numpy as np

In [2]:
def apply_wigner(X, Y, Z, alpha, beta, gamma):
    X, Y, Z = calc.vrot(X, Y, Z, alpha, Z)
    X, Y, Z = calc.vrot(X, Y, Z, beta, Y)
    X, Y, Z = calc.vrot(X, Y, Z, gamma, Z)
    return X, Y, Z

In [5]:
X = np.array([1, 0, 0])
Y = np.array([0, 1, 0])
Z = np.array([0, 0, 1])
center = np.array([0, 0, 0])

Xr, Yr, Zr = apply_wigner(X, Y, Z, np.pi/4., 0, 0)
Xb, Yb, Zb = apply_wigner(Xr, Yr, Zr, 0, 0.2, 0)
Xg, Yg, Zg = apply_wigner(Xb, Yb, Zb, 0, 0, 0.5)

Xl, Yl, Zl = apply_wigner(X, Y, Z, np.pi/4., 0.2, 0.5)

print("Indirect: ")
print(Xg)
print(Yg)
print(Zg)
print("Direct. :")
print(Xl)
print(Yl)
print(Zl)



Indirect: 
[ 0.26916995  0.94718005 -0.17434874]
[-0.9527921   0.28829706  0.09524715]
[0.14048043 0.14048043 0.98006658]
Direct. :
[ 0.26916995  0.94718005 -0.17434874]
[-0.9527921   0.28829706  0.09524715]
[0.14048043 0.14048043 0.98006658]


In [13]:
X = np.array([1, 1, 0])
X = X / np.linalg.norm(X)
Y = np.array([1, -1, 0])
Y = Y / np.linalg.norm(Y)
Z = np.cross(X, Y)
print(X)
print(Y)
print(Z)
print(np.dot(X, Y))
print(np.dot(X, Z))
print(np.dot(Y, Z))

center = np.array([0, 0, 0])

Xl, Yl, Zl = apply_wigner(X, Y, Z, 0.3, 0, 0)

p = nv.show_pdbid("6A5J")
p.clear_representations(0)

Xt = 10 * X
Yt = 10 * Y
Zt = 10 * Z

Xlt = 10 * Xl
Ylt = 10 * Yl
Zlt = 10 * Zl

p.shape.add_arrow([0, 0, 0], Xt.tolist(), [1, 0, 0], 0.5)
p.shape.add_arrow([0, 0, 0], Yt.tolist(), [0, 1, 0], 0.5)
p.shape.add_arrow([0, 0, 0], Zt.tolist(), [0, 0, 1], 0.5)
p.shape.add_arrow([0, 0, 0], Xlt.tolist(), [1, 0, 0], 1)
p.shape.add_arrow([0, 0, 0], Ylt.tolist(), [0, 1, 0], 1)
p.shape.add_arrow([0, 0, 0], Zlt.tolist(), [0, 0, 1], 1)
p

[0.70710678 0.70710678 0.        ]
[ 0.70710678 -0.70710678  0.        ]
[ 0.  0. -1.]
0.0
0.0
0.0


NGLWidget()